apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-demo-deployment
  labels:
    app: fastapi-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-demo
  template:
    metadata:
      labels:
        app: fastapi-demo
    spec:
      containers:
        - name: fastapi-demo-container
          image: fromwindowstolinux/fastapi-demo:latest
          args: ["run", "main.py"]
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo-service
  labels:
    app: fastapi-demo
spec:
  selector:
    app: fastapi-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
